import bcrypt from 'bcryptjs';
import { v4 as uuidv4 } from 'uuid';
import { assessLivestockRisk } from '../ai/riskAssessor.js';

export async function generateSeedData() {
  const passwordHash = await bcrypt.hash('pashu123', 10);

  // 1. Users
  const users = [
    {
      id: 'usr_farmer_01',
      email: 'farmer@pashurakshak.gov.in',
      phone: '+919822012345',
      password_hash: passwordHash,
      full_name: 'Ramesh Tukaram Patil',
      role: 'FARMER',
      district: 'Pune',
      taluka: 'Shirur',
      village: 'Nighoj',
      language_pref: 'mr',
    },
    {
      id: 'usr_farmer_02',
      email: 'ganesh.more@pashurakshak.gov.in',
      phone: '+919822098765',
      password_hash: passwordHash,
      full_name: 'Ganesh Bhausaheb More',
      role: 'FARMER',
      district: 'Ahmednagar',
      taluka: 'Parner',
      village: 'Supe',
      language_pref: 'mr',
    },
    {
      id: 'usr_vet_01',
      email: 'vet@pashurakshak.gov.in',
      phone: '+919423011223',
      password_hash: passwordHash,
      full_name: 'Dr. Anand Deshmukh (B.V.Sc & A.H)',
      role: 'FIELD_VET',
      district: 'Pune',
      taluka: 'Shirur',
      village: 'Shirur Central Hospital',
      language_pref: 'en',
    },
    {
      id: 'usr_paravet_01',
      email: 'paravet@pashurakshak.gov.in',
      phone: '+919765432100',
      password_hash: passwordHash,
      full_name: 'Sunil Shinde (Livestock Supervisor)',
      role: 'PARA_VET',
      district: 'Pune',
      taluka: 'Shirur',
      village: 'Nighoj Sub-Center',
      language_pref: 'mr',
    },
    {
      id: 'usr_lab_01',
      email: 'lab@pashurakshak.gov.in',
      phone: '+919823145678',
      password_hash: passwordHash,
      full_name: 'Dr. Priya Kulkarni (Senior Pathologist)',
      role: 'LAB_TECH',
      district: 'Pune',
      taluka: 'Haveli',
      village: 'District Animal Disease Diagnostic Lab, Aundh, Pune',
      language_pref: 'en',
    },
    {
      id: 'usr_district_admin_01',
      email: 'district.admin@pashurakshak.gov.in',
      phone: '+919422001122',
      password_hash: passwordHash,
      full_name: 'Sanjay Jadhav (District Animal Husbandry Officer)',
      role: 'DISTRICT_ADMIN',
      district: 'Pune',
      taluka: 'Pune City',
      village: 'District Collectorate Office',
      language_pref: 'mr',
    },
    {
      id: 'usr_state_admin_01',
      email: 'state.admin@pashurakshak.gov.in',
      phone: '+919820003344',
      password_hash: passwordHash,
      full_name: 'Dr. Vilas Gaikwad (State Livestock Surveillance Director)',
      role: 'STATE_ADMIN',
      district: 'Mumbai City',
      taluka: 'Mantralaya',
      village: 'Animal Husbandry Commissionerate',
      language_pref: 'en',
    }
  ];

  // 2. Farmer Profiles
  const farmerProfiles = [
    {
      user_id: 'usr_farmer_01',
      aadhar_last4: '4589',
      farm_size_acres: 4.5,
      total_cattle: 4,
      total_buffalo: 2,
      total_goats: 6,
      total_sheep: 0,
      total_poultry: 15
    },
    {
      user_id: 'usr_farmer_02',
      aadhar_last4: '7812',
      farm_size_acres: 6.0,
      total_cattle: 5,
      total_buffalo: 3,
      total_goats: 10,
      total_sheep: 0,
      total_poultry: 0
    }
  ];

  // 3. Veterinary Workers
  const vetWorkers = [
    {
      user_id: 'usr_vet_01',
      registration_no: 'MSVC-2014-08942',
      designation: 'Taluka Veterinary Officer Class-I',
      assigned_taluka: 'Shirur',
      assigned_district: 'Pune',
      center_name: 'Shirur Government Veterinary Polyclinic',
      phone_emergency: '+919423011223'
    },
    {
      user_id: 'usr_paravet_01',
      registration_no: 'PV-MAH-2018-441',
      designation: 'Para-Veterinary Field Officer',
      assigned_taluka: 'Shirur',
      assigned_district: 'Pune',
      center_name: 'Nighoj Primary Veterinary Aid Center',
      phone_emergency: '+919765432100'
    }
  ];

  // 4. Livestock (Maharashtra breeds with realistic coordinates)
  const livestock = [
    {
      id: 'ani_cow_01',
      ear_tag_id: 'MH-PUN-001892',
      species: 'Cattle',
      breed: 'Gir Crossbred',
      sex: 'FEMALE',
      age_months: 38,
      owner_id: 'usr_farmer_01',
      village: 'Nighoj',
      taluka: 'Shirur',
      district: 'Pune',
      latitude: 18.8247,
      longitude: 74.3412,
      health_status: 'SICK',
      vaccination_status: 'OVERDUE',
      last_vaccination_date: '2025-08-10',
      next_vaccination_due: '2026-02-10',
      previous_diseases: JSON.stringify(['Mastitis (2024)']),
      photo_url: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=600&auto=format&fit=crop&q=80',
    },
    {
      id: 'ani_cow_02',
      ear_tag_id: 'MH-PUN-001893',
      species: 'Cattle',
      breed: 'Khillari',
      sex: 'MALE',
      age_months: 48,
      owner_id: 'usr_farmer_01',
      village: 'Nighoj',
      taluka: 'Shirur',
      district: 'Pune',
      latitude: 18.8251,
      longitude: 74.3418,
      health_status: 'HEALTHY',
      vaccination_status: 'UP_TO_DATE',
      last_vaccination_date: '2026-06-15',
      next_vaccination_due: '2026-12-15',
      previous_diseases: JSON.stringify([]),
      photo_url: 'https://images.unsplash.com/photo-1546445317-29f4545e9d53?w=600&auto=format&fit=crop&q=80',
    },
    {
      id: 'ani_buf_01',
      ear_tag_id: 'MH-PUN-002144',
      species: 'Buffalo',
      breed: 'Murrah',
      sex: 'FEMALE',
      age_months: 42,
      owner_id: 'usr_farmer_01',
      village: 'Nighoj',
      taluka: 'Shirur',
      district: 'Pune',
      latitude: 18.8245,
      longitude: 74.3409,
      health_status: 'HEALTHY',
      vaccination_status: 'UP_TO_DATE',
      last_vaccination_date: '2026-05-20',
      next_vaccination_due: '2026-11-20',
      previous_diseases: JSON.stringify([]),
      photo_url: 'https://images.unsplash.com/photo-1563281577-a7be47e20db9?w=600&auto=format&fit=crop&q=80',
    },
    {
      id: 'ani_goat_01',
      ear_tag_id: 'MH-PUN-003319',
      species: 'Goat',
      breed: 'Osmanabadi',
      sex: 'FEMALE',
      age_months: 18,
      owner_id: 'usr_farmer_01',
      village: 'Nighoj',
      taluka: 'Shirur',
      district: 'Pune',
      latitude: 18.8242,
      longitude: 74.3415,
      health_status: 'HEALTHY',
      vaccination_status: 'UP_TO_DATE',
      last_vaccination_date: '2026-04-10',
      next_vaccination_due: '2026-10-10',
      previous_diseases: JSON.stringify([]),
      photo_url: 'https://images.unsplash.com/photo-1524024973431-2ad916746881?w=600&auto=format&fit=crop&q=80',
    },
    {
      id: 'ani_cow_03',
      ear_tag_id: 'MH-AHM-008921',
      species: 'Cattle',
      breed: 'Holstein Friesian Cross',
      sex: 'FEMALE',
      age_months: 30,
      owner_id: 'usr_farmer_02',
      village: 'Supe',
      taluka: 'Parner',
      district: 'Ahmednagar',
      latitude: 18.9812,
      longitude: 74.4124,
      health_status: 'SICK',
      vaccination_status: 'OVERDUE',
      last_vaccination_date: '2025-07-22',
      next_vaccination_due: '2026-01-22',
      previous_diseases: JSON.stringify([]),
      photo_url: 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=600&auto=format&fit=crop&q=80',
    },
    {
      id: 'ani_cow_04',
      ear_tag_id: 'MH-KOL-003412',
      species: 'Cattle',
      breed: 'Dangi',
      sex: 'FEMALE',
      age_months: 52,
      owner_id: 'usr_farmer_01',
      village: 'Karve',
      taluka: 'Chandgad',
      district: 'Kolhapur',
      latitude: 15.9123,
      longitude: 74.2215,
      health_status: 'UNDER_TREATMENT',
      vaccination_status: 'UP_TO_DATE',
      last_vaccination_date: '2026-03-12',
      next_vaccination_due: '2026-09-12',
      previous_diseases: JSON.stringify(['Foot and Mouth Disease (2025)']),
      photo_url: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=600&auto=format&fit=crop&q=80',
    }
  ];

  // 5. Health Reports & Initial AI assessments
  const reports = [
    {
      id: 'rep_lsd_001',
      local_id: 'loc_rep_001',
      animal_id: 'ani_cow_01',
      reporter_id: 'usr_farmer_01',
      symptoms: JSON.stringify(['Fever', 'Skin lesions', 'Reduced milk production', 'Excessive salivation']),
      severity: 'HIGH',
      temperature_f: 104.8,
      photo_url: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=600&auto=format&fit=crop&q=80',
      audio_url: null,
      latitude: 18.8247,
      longitude: 74.3412,
      village: 'Nighoj',
      taluka: 'Shirur',
      district: 'Pune',
      status: 'SAMPLE_REQUIRED',
      assigned_vet_id: 'usr_vet_01',
      vet_notes: 'Clinical signs strongly indicate Lumpy Skin Disease (LSD). High fever, firm nodular cutaneous eruptions across neck and torso. Ordered diagnostic swab & blood sample for PCR confirmation. Advised strict animal isolation.',
      diagnosis: 'Suspected Lumpy Skin Disease (Capripoxvirus)',
      treatment_plan: '1. Isolation in insect-screened shed. 2. Antipyretic: Meloxicam 0.5 mg/kg IM. 3. Antiseptic spray on ulcerated nodules. 4. Supportive Vitamin B-Complex.',
      quarantine_ordered: 1,
      sync_status: 'SYNCED',
      created_at: new Date(Date.now() - 3600000 * 18).toISOString(), // 18 hours ago
    },
    {
      id: 'rep_fmd_002',
      local_id: 'loc_rep_002',
      animal_id: 'ani_cow_03',
      reporter_id: 'usr_farmer_02',
      symptoms: JSON.stringify(['Excessive salivation', 'Lameness', 'Fever', 'Loss of appetite']),
      severity: 'HIGH',
      temperature_f: 103.5,
      photo_url: 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=600&auto=format&fit=crop&q=80',
      audio_url: null,
      latitude: 18.9812,
      longitude: 74.4124,
      village: 'Supe',
      taluka: 'Parner',
      district: 'Ahmednagar',
      status: 'LAB_PENDING',
      assigned_vet_id: 'usr_vet_01',
      vet_notes: 'Profuse ropy salivation and erosions on interdigital space. Sample collected and sent to Pune Disease Diagnostic Lab.',
      diagnosis: 'Foot and Mouth Disease (FMD Type O Suspect)',
      treatment_plan: 'Potassium permanganate mouth wash, antiseptic foot bath, Boroglycerine application.',
      quarantine_ordered: 1,
      sync_status: 'SYNCED',
      created_at: new Date(Date.now() - 3600000 * 36).toISOString(),
    },
    {
      id: 'rep_fmd_003',
      local_id: 'loc_rep_003',
      animal_id: 'ani_cow_04',
      reporter_id: 'usr_farmer_01',
      symptoms: JSON.stringify(['Lameness', 'Reduced milk production']),
      severity: 'MEDIUM',
      temperature_f: 101.2,
      photo_url: null,
      audio_url: null,
      latitude: 15.9123,
      longitude: 74.2215,
      village: 'Karve',
      taluka: 'Chandgad',
      district: 'Kolhapur',
      status: 'TREATMENT_STARTED',
      assigned_vet_id: 'usr_vet_01',
      vet_notes: 'Interdigital pododermatitis (Foot rot). Treated with topical zinc sulphate and parenteral antibiotics.',
      diagnosis: 'Bovine Foot Rot (Interdigital Necrobacillosis)',
      treatment_plan: 'Oxytetracycline LA 20mg/kg deep IM, foot dip daily.',
      quarantine_ordered: 0,
      sync_status: 'SYNCED',
      created_at: new Date(Date.now() - 3600000 * 72).toISOString(),
    }
  ];

  // 6. Lab Samples
  const labSamples = [
    {
      id: 'lab_smp_001',
      sample_code: 'LAB-PUN-2026-089',
      report_id: 'rep_lsd_001',
      animal_id: 'ani_cow_01',
      disease_suspected: 'Lumpy Skin Disease (LSD)',
      sample_type: 'Skin Scab & EDTA Blood',
      collection_date: new Date(Date.now() - 3600000 * 12).toISOString(),
      collected_by: 'Dr. Anand Deshmukh',
      dispatch_date: new Date(Date.now() - 3600000 * 10).toISOString(),
      lab_name: 'District Animal Disease Diagnostic Laboratory, Aundh, Pune',
      lab_received_date: new Date(Date.now() - 3600000 * 6).toISOString(),
      test_type: 'Capripoxvirus Real-time PCR',
      status: 'TESTING',
      result: 'PENDING',
      confirmed_disease: null,
      test_notes: 'Sample received in cold chain. DNA extraction completed; PCR amplification underway in Thermocycler Block B.',
      tested_by: 'Dr. Priya Kulkarni',
    },
    {
      id: 'lab_smp_002',
      sample_code: 'LAB-AHM-2026-042',
      report_id: 'rep_fmd_002',
      animal_id: 'ani_cow_03',
      disease_suspected: 'Foot and Mouth Disease (FMD)',
      sample_type: 'Epithelial Tissue & Vesicular Swab',
      collection_date: new Date(Date.now() - 3600000 * 30).toISOString(),
      collected_by: 'Dr. Anand Deshmukh',
      dispatch_date: new Date(Date.now() - 3600000 * 26).toISOString(),
      lab_name: 'District Animal Disease Diagnostic Laboratory, Aundh, Pune',
      lab_received_date: new Date(Date.now() - 3600000 * 20).toISOString(),
      test_type: 'FMD Antigen Sandwich ELISA (Serotype Typing)',
      status: 'RESULT_AVAILABLE',
      result: 'POSITIVE',
      confirmed_disease: 'FMD Virus Serotype O (Confirmed)',
      test_notes: 'Strong positive reaction on ELISA Optical Density reading (OD 1.84). High viral titer confirmed.',
      tested_by: 'Dr. Priya Kulkarni',
      completed_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    }
  ];

  // 7. Vaccinations
  const vaccinations = [
    {
      id: 'vac_rec_001',
      animal_id: 'ani_cow_02',
      vaccine_name: 'Goat Pox Vaccine (LSD Ring Protection)',
      batch_no: 'GPV-MAH-2026/04',
      dose_number: 1,
      administered_date: '2026-06-15',
      next_due_date: '2026-12-15',
      administered_by: 'Dr. Anand Deshmukh',
      status: 'COMPLETED',
      remarks: 'Subcutaneous injection 1ml. No post-vaccination adverse events.'
    },
    {
      id: 'vac_rec_002',
      animal_id: 'ani_buf_01',
      vaccine_name: 'Raksha-Ovac Quadrivalent FMD Vaccine',
      batch_no: 'FMD-RO-2026-88',
      dose_number: 2,
      administered_date: '2026-05-20',
      next_due_date: '2026-11-20',
      administered_by: 'Sunil Shinde',
      status: 'COMPLETED',
      remarks: 'Routine bi-annual vaccination drive.'
    },
    {
      id: 'vac_rec_003',
      animal_id: 'ani_goat_01',
      vaccine_name: 'PPR Live Attenuated Vaccine',
      batch_no: 'PPR-L-2026-11',
      dose_number: 1,
      administered_date: '2026-04-10',
      next_due_date: '2027-04-10',
      administered_by: 'Sunita More',
      status: 'COMPLETED',
      remarks: 'Administered under National PPR Eradication Programme.'
    },
    {
      id: 'vac_rec_004',
      animal_id: 'ani_cow_04',
      vaccine_name: 'Haemorrhagic Septicaemia Oil Adjuvant Vaccine (HS)',
      batch_no: 'HS-OA-2026-52',
      dose_number: 1,
      administered_date: '2026-03-12',
      next_due_date: '2027-03-12',
      administered_by: 'Dr. Priya Kulkarni',
      status: 'COMPLETED',
      remarks: 'Pre-monsoon booster dose administered.'
    },
    {
      id: 'vac_rec_005',
      animal_id: 'ani_cow_01',
      vaccine_name: 'Brucellosis S19 Calfhood Vaccine',
      batch_no: 'BRU-S19-2025-99',
      dose_number: 1,
      administered_date: '2025-11-05',
      next_due_date: '2027-11-05',
      administered_by: 'Dr. Anand Deshmukh',
      status: 'COMPLETED',
      remarks: 'Single dose calfhood immunization.'
    }
  ];

  // 8. Vaccination Campaigns
  const campaigns = [
    {
      id: 'cmp_lsd_pune_01',
      title: 'Mission PashuRaksha: Emergency LSD Ring Vaccination Drive',
      disease_target: 'Lumpy Skin Disease (LSD)',
      district: 'Pune',
      talukas: JSON.stringify(['Shirur', 'Haveli', 'Khed', 'Daund']),
      start_date: '2026-09-15',
      end_date: '2026-10-15',
      target_count: 50000,
      achieved_count: 36420,
      status: 'ACTIVE'
    },
    {
      id: 'cmp_fmd_state_02',
      title: 'Statewide FMD National Animal Disease Control Programme (NADCP Phase IV)',
      disease_target: 'Foot and Mouth Disease (FMD)',
      district: 'Maharashtra (All 36 Districts)',
      talukas: JSON.stringify(['All']),
      start_date: '2026-08-01',
      end_date: '2026-11-30',
      target_count: 1200000,
      achieved_count: 885400,
      status: 'ACTIVE'
    }
  ];

  // 9. Spatiotemporal Outbreak Clusters
  const outbreaks = [
    {
      id: 'out_pune_shirur_01',
      outbreak_code: 'OB-PUN-2026-01',
      disease: 'Lumpy Skin Disease (LSD)',
      district: 'Pune',
      taluka: 'Shirur',
      epicenter_village: 'Nighoj',
      center_lat: 18.8247,
      center_lng: 74.3412,
      radius_km: 8.5,
      affected_villages_count: 7,
      active_cases_count: 23,
      mortality_count: 2,
      risk_level: 'HIGH',
      detected_date: '2026-09-20',
      containment_zone_active: 1,
      assigned_rapid_response_team: 'Pune Rapid Veterinary Taskforce #3',
      advisory_broadcast_sent: 1
    },
    {
      id: 'out_ahm_parner_02',
      outbreak_code: 'OB-AHM-2026-04',
      disease: 'Foot and Mouth Disease (FMD)',
      district: 'Ahmednagar',
      taluka: 'Parner',
      epicenter_village: 'Supe',
      center_lat: 18.9812,
      center_lng: 74.4124,
      radius_km: 12.0,
      affected_villages_count: 11,
      active_cases_count: 38,
      mortality_count: 1,
      risk_level: 'HIGH',
      detected_date: '2026-09-18',
      containment_zone_active: 1,
      assigned_rapid_response_team: 'Ahmednagar District Disease Control Unit',
      advisory_broadcast_sent: 1
    },
    {
      id: 'out_satara_karad_03',
      outbreak_code: 'OB-SAT-2026-02',
      disease: 'Hemorrhagic Septicemia (HS)',
      district: 'Satara',
      taluka: 'Karad',
      epicenter_village: 'Ond',
      center_lat: 17.2890,
      center_lng: 74.1812,
      radius_km: 5.0,
      affected_villages_count: 3,
      active_cases_count: 8,
      mortality_count: 3,
      risk_level: 'CRITICAL',
      detected_date: '2026-09-24',
      containment_zone_active: 1,
      assigned_rapid_response_team: 'Satara Mobile Veterinary Emergency Van #1',
      advisory_broadcast_sent: 1
    }
  ];

  // 10. Alerts & Notifications
  const alerts = [
    {
      id: 'alt_001',
      alert_type: 'HIGH_RISK_ANIMAL',
      title: 'Lumpy Skin Disease Suspected (Ear Tag: MH-PUN-001892)',
      message: 'AI Risk Engine scored 84/100 risk for Cattle in Nighoj, Shirur. Veterinary exam and quarantine initiated.',
      severity: 'CRITICAL',
      target_role: 'FIELD_VET',
      target_district: 'Pune',
      target_taluka: 'Shirur',
      target_user_id: 'usr_vet_01',
      related_report_id: 'rep_lsd_001',
      is_read: 0,
      created_at: new Date(Date.now() - 3600000 * 18).toISOString()
    },
    {
      id: 'alt_002',
      alert_type: 'POSSIBLE_OUTBREAK',
      title: 'Spatiotemporal Cluster Alert: Shirur Taluka (Pune)',
      message: '23 active LSD cases detected across 7 adjoining villages. Baseline deviation exceeds 3.8x. Containment zone active.',
      severity: 'CRITICAL',
      target_role: 'DISTRICT_ADMIN',
      target_district: 'Pune',
      target_taluka: 'Shirur',
      target_user_id: null,
      related_report_id: 'rep_lsd_001',
      is_read: 0,
      created_at: new Date(Date.now() - 3600000 * 14).toISOString()
    },
    {
      id: 'alt_003',
      alert_type: 'CONTAINMENT_ADVISORY',
      title: 'लम्पी त्वचा रोग सतर्कता सूचना (Advisory for Farmers)',
      message: 'शिरूर तालुक्यातील शेतकरी बांधवांना आवाहन: जनावरांमध्ये गाठी किंवा ताप आढळल्यास त्वरित पशुवैद्यकीय दवाखान्याशी संपर्क साधावा. जनावरांचा बाजार बंद ठेवण्यात आला आहे.',
      severity: 'WARNING',
      target_role: 'FARMER',
      target_district: 'Pune',
      target_taluka: 'Shirur',
      target_user_id: null,
      related_report_id: null,
      is_read: 0,
      created_at: new Date(Date.now() - 3600000 * 10).toISOString()
    },
    {
      id: 'alt_004',
      alert_type: 'LAB_RESULT_AVAILABLE',
      title: 'Lab Result Confirmed: FMD Positive (Sample LAB-AHM-2026-042)',
      message: 'ELISA test confirmed Foot & Mouth Disease Serotype O. Ring vaccination required for surrounding 5km radius in Parner taluka.',
      severity: 'CRITICAL',
      target_role: 'FIELD_VET',
      target_district: 'Ahmednagar',
      target_taluka: 'Parner',
      target_user_id: null,
      related_report_id: 'rep_fmd_002',
      is_read: 0,
      created_at: new Date(Date.now() - 3600000 * 2).toISOString()
    }
  ];

  // 11. Audit Logs
  const auditLogs = [
    {
      id: 'aud_001',
      user_id: 'usr_farmer_01',
      user_name: 'Ramesh Tukaram Patil',
      user_role: 'FARMER',
      action: 'CREATE_HEALTH_REPORT',
      entity: 'HealthReport',
      entity_id: 'rep_lsd_001',
      prev_value: null,
      new_value: JSON.stringify({ animal: 'MH-PUN-001892', symptoms: ['Fever', 'Skin lesions'], severity: 'HIGH' }),
      ip_address: '192.168.1.45',
      timestamp: new Date(Date.now() - 3600000 * 18).toISOString()
    },
    {
      id: 'aud_002',
      user_id: 'usr_vet_01',
      user_name: 'Dr. Anand Deshmukh',
      user_role: 'FIELD_VET',
      action: 'VET_CLINICAL_EXAMINATION',
      entity: 'HealthReport',
      entity_id: 'rep_lsd_001',
      prev_value: 'OPEN',
      new_value: 'SAMPLE_REQUIRED',
      ip_address: '192.168.1.12',
      timestamp: new Date(Date.now() - 3600000 * 12).toISOString()
    },
    {
      id: 'aud_003',
      user_id: 'usr_lab_01',
      user_name: 'Dr. Priya Kulkarni',
      user_role: 'LAB_TECH',
      action: 'ENTER_LAB_RESULT',
      entity: 'LabSample',
      entity_id: 'lab_smp_002',
      prev_value: 'TESTING',
      new_value: 'RESULT_AVAILABLE (POSITIVE)',
      ip_address: '192.168.1.88',
      timestamp: new Date(Date.now() - 3600000 * 2).toISOString()
    }
  ];

  return {
    users,
    farmerProfiles,
    vetWorkers,
    livestock,
    reports,
    labSamples,
    vaccinations,
    campaigns,
    outbreaks,
    alerts,
    auditLogs
  };
}
